import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { SessionProvider } from 'next-auth/react';
import { useState } from "react";
import { useRouter } from "next/navigation";


export const metadata: Metadata = {
  title: "Itinefy",
  description: "Generated by create next app",
};
const inter = Inter({ subsets :["latin"]})

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode;}>)
{
 

  return (
    <html lang="en"  suppressHydrationWarning>
      <head>
        <meta name="robots" content="=noindex,nofollow"/>
      </head>
      <SessionProvider>
      <body
      className={inter.className}
      >
        {children}
        
      </body>
      </SessionProvider>
    </html>
  );
}
